language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot

matrix:
  allow_failures:
  - php: 7.2
  - php: 7.4snapshot

before_script:
  - composer update --prefer-stable

script: ./vendor/bin/phpunit

after_script:
    - php vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml
